
export class StrategyCodeInsertion {
  static insertCodeSnippet(existingCode: string, snippet: string, title: string): string {
    if (!existingCode.trim()) {
      // If editor is empty, create a basic strategy structure with the snippet
      return `# Strategy with ${title}
# Generated by Strategy Coach

def strategy_logic(data):
    # ${title}
    ${snippet}
    
    # Basic structure - modify as needed
    entry = []
    exit = []
    
    for i in range(len(data)):
        if i == 0:
            entry.append(False)
            exit.append(False)
        else:
            # Add your entry/exit logic here
            entry.append(False)  # Replace with your entry condition
            exit.append(False)   # Replace with your exit condition
    
    return {
        'entry': entry,
        'exit': exit
    }`;
    }

    // Check if snippet already exists to prevent duplicates
    if (existingCode.includes(snippet.trim())) {
      return existingCode;
    }

    // Find the strategy_logic function and insert the snippet
    const functionMatch = existingCode.match(/def strategy_logic\(data\):([\s\S]*?)(?=\n\ndef|\n# Alternative|\n$|$)/);
    
    if (functionMatch) {
      const functionBody = functionMatch[1];
      const insertionPoint = functionBody.search(/(?=\s*entry\s*=|return\s*\{)/);
      
      if (insertionPoint !== -1) {
        // Insert before entry/return logic
        const beforeInsertion = functionBody.substring(0, insertionPoint);
        const afterInsertion = functionBody.substring(insertionPoint);
        
        const newFunctionBody = `${beforeInsertion}
    # ${title} (Strategy Coach Suggestion)
    ${snippet}
    ${afterInsertion}`;

        return existingCode.replace(functionMatch[0], `def strategy_logic(data):${newFunctionBody}`);
      } else {
        // Append at the end of the function body
        const newFunctionBody = `${functionBody}
    
    # ${title} (Strategy Coach Suggestion)
    ${snippet}`;

        return existingCode.replace(functionMatch[0], `def strategy_logic(data):${newFunctionBody}`);
      }
    } else {
      // Append as a comment at the end if no strategy_logic function found
      return `${existingCode}

# ${title} (Strategy Coach Suggestion)
# ${snippet}`;
    }
  }
}
