// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnlxhokpdqqnvustvgds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubHhob2twZHFxbnZ1c3R2Z2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDQyOTcsImV4cCI6MjA2NDAyMDI5N30.3UMUcuDHXqmtyLcp3vhYa4Kwuwe5a6Fl8l-zjLaPLhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);